apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonatype-nexus
  labels:
    app: sonatype-nexus
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    server: 192.168.2.11
    path: /nfs/data/nexus

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonatype-nexus
  labels:
    app: sonatype-nexus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: sonatype-nexus